version: 4.6.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
environment:
  CI: true
  RUBY_VERSION: 23
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - gem install bundler --conservative
  - bundle config --local path vendor/bundle
  - bundle install
  - dotnet --version




build_script:
- cmd: >-
    rake ci
test: off

artifacts:
  - path: '**\*.*.nupkg' # find all NuGet packages recursively
